modLoader = "javafml"
loaderVersion = "[4,)"
license = "LGPL-3.0-only"

[[mods]]
modId = "justbrightness"
version = "${version}"
displayName = "Just Brightness"
description = "Toggle a fullbright-style gamma override on demand."

[[mixins]]
config="justbrightness.mixins.json"

[[dependencies.justbrightness]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.justbrightness]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "CLIENT"
